Repository P-pick/front, pull requests merged in 2025-06, with the labels that each got.

#13 geotrip 페이지 스와이프 추가
  package.json
  pnpm-lock.yaml
  public/지도.webp
  src/App.tsx
  src/components/BackButton.tsx
  src/components/MenuIcon.tsx
  src/components/index.ts
  src/config/QueryProvider.tsx
  src/config/Router.tsx
  src/config/instance.ts
  src/pages/geotrip/GeoTrip.tsx
  src/pages/geotrip/components/DistanceTimeInfo.tsx
  src/pages/geotrip/components/GetCurrentGeoLocation.tsx
  src/pages/geotrip/components/TourSlide.tsx
  src/pages/geotrip/components/TourSwiperWithLocation.tsx
  src/pages/geotrip/components/index.ts
  src/pages/geotrip/const.ts
  src/pages/geotrip/index.ts
  src/pages/geotrip/lib/getCurrentLocation.ts
  src/pages/geotrip/lib/index.ts
  src/pages/geotrip/lib/truncate.ts
  src/pages/geotrip/service/getLocationBasedData.ts
  src/pages/geotrip/service/index.ts
  src/pages/geotrip/types.d.ts
  src/pages/home/Home.tsx
  src/pages/types.d.ts
  src/styles.css
  tailwind.config.ts
Labels: feature

#20 geoAround geoDestination 폴더 분리
  package.json
  pnpm-lock.yaml
  src/pages/geoMap/GeoMap.tsx
  src/pages/geoMap/components/GeoAroundTouristMap.tsx
  src/pages/geoMap/components/geoAroundTourist/AroundTouristNavigate.tsx
  src/pages/geoMap/components/geoAroundTourist/DetailsOfNearbyTouristAttractions.tsx
  src/pages/geoMap/components/geoAroundTourist/NearbyTouristAttractionPinpoint.tsx
  src/pages/geoMap/components/geoAroundTourist/index.ts
  src/pages/geoMap/components/geoDestination/index.ts
  src/pages/geoMap/components/index.ts
Labels: modify

#21 여행 상세보기 구현
  src/components/BottomSheet.tsx
  src/components/index.ts
  src/lib/useCurrentLocation.ts
  src/pages/geotrip/GeoTrip.tsx
  src/pages/geotrip/components/DistanceTimeInfo.tsx
  src/pages/geotrip/components/GeoTripInitializer.tsx
  src/pages/geotrip/components/GetCurrentGeoLocation.tsx
  src/pages/geotrip/components/TourDetail.tsx
  src/pages/geotrip/components/TourResultSwiper.tsx
  src/pages/geotrip/components/TourSlide.tsx
  src/pages/geotrip/components/TourSwiperWithLocation.tsx
  src/pages/geotrip/components/index.ts
  src/pages/geotrip/lib/getCurrentLocation.ts
  src/pages/geotrip/service/getLocationBasedData.ts
  src/pages/types.d.ts
  src/styles.css
Labels: feature

#26 TTS 기능 추가
  package.json
  pnpm-lock.yaml
  src/pages/geotrip/components/GeoTripInitializer.tsx
  src/pages/geotrip/components/SideButtonGroup/PlayTTSButton.tsx
  src/pages/geotrip/components/SideButtonGroup/SideButtonGroup.tsx
  src/pages/geotrip/components/SideButtonGroup/index.tsx
  src/pages/geotrip/components/TourDetail.tsx
  src/pages/geotrip/components/TourResultSwiper.tsx
  src/pages/geotrip/components/TourSlide.tsx
  src/pages/geotrip/lib/index.ts
  src/pages/geotrip/lib/useTTS.ts
  src/pages/geotrip/service/index.ts
  src/pages/geotrip/service/pollyTTS.ts
  src/pages/geotrip/types.d.ts
Labels: feature

#28 타입 폴더 분리
  src/lib/useCurrentLocation.ts
  src/pages/geoMap/components/geoAroundTourist/GeoAroundTouristMap.tsx
  src/pages/geoMap/components/geoDestination/GeoDestinationMap.tsx
  src/pages/geoMap/lib/transportation/getPolyLinesCarPathInfo.ts
  src/pages/geoMap/lib/transportation/getPolyLinesPedestrianPath.ts
  src/pages/geoMap/lib/transportation/getSelectedTransportationPolylines.ts
  src/pages/geoMap/lib/transportation/index.ts
  src/pages/geoMap/lib/utils/isValidationLocation.ts
  src/pages/geoMap/service/getTransportationSelected.ts
  src/pages/geoMap/types.d.ts
  src/pages/geoMap/types/carType.d.ts
  src/pages/geoMap/types/index.ts
  src/pages/geoMap/types/pedestrianType.d.ts
Labels: refactor

#29 기존 polylines 배열 하나로 불러오던 걸 컴포넌트로 분리
  public/Point.png
  src/pages/geoMap/components/geoDestination/DestinationDetail.tsx
  src/pages/geoMap/components/geoDestination/GeoDestinationMap.tsx
  src/pages/geoMap/components/geoDestination/polylines/CarPolylines.tsx
  src/pages/geoMap/components/geoDestination/polylines/GetPolylines.tsx
  src/pages/geoMap/components/geoDestination/polylines/PedestrianPolylines.tsx
  src/pages/geoMap/components/geoDestination/polylines/Point.tsx
  src/pages/geoMap/components/geoDestination/polylines/index.ts
  src/pages/geoMap/lib/transportation/getPolyLinesCarPathInfo.ts
  src/pages/geoMap/lib/transportation/getPolyLinesPedestrianPath.ts
  src/pages/geoMap/lib/transportation/index.ts
  src/pages/geoMap/lib/utils/gettingConversion.ts
  src/pages/geoMap/lib/utils/index.ts
  src/pages/geoMap/service/getCarData.ts
  src/pages/geoMap/service/getTransportationSelected.ts
  src/pages/geoMap/types/index.ts
Labels: modify

#30 이동수단 선택 UI변경
  src/assets/DeleteIcon.svg
  src/assets/RightIcon.svg
  src/assets/carIcon.svg
  src/assets/endPoint.svg
  src/assets/index.ts
  src/assets/pedestrianIcon.svg
  src/assets/rideIcon.svg
  src/assets/startPoint.svg
  src/assets/transportationIcon.svg
  src/pages/const/TRANSPORT.tsx
  src/pages/geoMap/components/geoDestination/DestinationDetail.tsx
  src/pages/geoMap/components/geoDestination/GeoDestinationMap.tsx
  src/pages/geoMap/components/geoDestination/SelectTransportationFromGeoMap.tsx
  src/pages/geoMap/components/geoDestination/polylines/index.ts
Labels: modify
